<a href="https://colab.research.google.com/github/ShreyaBadgaiyan/EI/blob/main/Internship_data_science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY


In [ ]:
import numpy as np

# In numpy we can onl work with array, array is a collection of homogenous type of data
#one , two dimnsional array

# a=[2,4,6,8,90]
# type(a)
#Typecasting list into numpy array

a=np.array([2,3,5,6,45])
type(a)

a.dtype
a.ndim
a.max()
a.min()
a.itemsize
a.size
a.sum()


61

In [ ]:
#1D ARRAY- Collection of homogenous elements
#2D ARRAY- Collection of 1D arrays
#3D ARRAY- Collection of 2D arrays
#ND ARRAY- Collection of N-1D arrays

#1D ARRAY
#Different ways to create  1D array
'''1)array()
2)arange()
3)linespace()
4)logspace()
5)ones()
6)zeros()'''

a1=np.array([23,45,24,67.8])
a1
#all values in float coz it needs to be homogenous

a2=np.array([2,4,5,2,56.7],dtype='int')
a2
#all value become integer

a3=np.array([23,45,24,67.8,"abc"])
a3
#all become string

a4=np.arange(2,9,2)
#start stop and step value needs be given
a4
type(a4)

a4=np.arange(2,9,0.5)
a4

#LINESPACE FUNCTION : linespace(start,stop,no. of elements)--so we specify the start and stop values and the number of values we want between then.
#It includes the last value,default no. of elements in between is 50
a5=np.linspace(1,18,37)
a5

a6=np.logspace(1,5,50)
a6
#gives log values in between

a7=np.zeros(67,dtype='int')
a7
#having only zeroes as values

a8=np.ones(89)
a8
#having only ones as values

a8[23]

1.0

In [ ]:
#2D array in numpy
#Collection of 1D array

a=np.array([
[22,33,455,67],
[2,3,5,6],
[1,2,4,5]])

a.ndim
a[0]
a[0][0]

a[1][1:3]
a[0][0:1]

# Slicing: remain in same dimension
# Indexing: decrease dimension by 1

a[0:1,0:1]
#in two dimesion slicing

a[0:2,1:3]
a[0:3:2,0:4:3]
a[::2,::3]
#getting all the corner elements


# Reshape function gives number of rows and columns separated by commas

a.shape

#To convert any array to 1D array, use ravel notion

a.ravel()
a.size
len(a)

# size=row*column

a.reshape(6,2)
a.reshape(2,6)


#Ways to create 2D arrays

#ARANGE
a2=np.arange(8).reshape(2,4)
a2

#LINSPACE
a3=np.linspace(2,4,20,dtype='int').reshape(5,4)
a3

a4=np.zeros(30).reshape(5,6)
a4

a5=np.ones(30).reshape(5,6)
a5

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
#THREE DIMENSIONAL ARRAY IN NUMPY
#Collection of 2D array in numpy
import numpy as np
a=np.array([[[1,2,4],[8,6,9],[2,2,3]],[[5,7,56],[46,89,56],[90,87,56]]])
a.ndim
a[0]
a[0][0]
a[0][0][1]
a
a[0][0:1][1:2,1:3]

a=np.arange(30).reshape(2,3,5)
a
#size=n*r*c

a.reshape(10,3)
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [ ]:

#RESHAPING -- Convert any nD array into any nD array is called Reshaping array in numpy.

#totl no. of element is size==r*c==n*r*c==n1*n2*r*c

a=np.arange(0,20,1)
a
a.ndim
b=a.reshape(4,5)
b
c=a.reshape(2,2,5)
c
a=np.arange(0,24,1)
d=a.reshape(2,2,2,3)
d




array([[[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]],


       [[[12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23]]]])